### PR TITLE
Add Chinese translations

### PR DESCRIPTION
**Pull request by morisenmen**

### CODE REVIEW

**Comment by kartik-v** [comment]
You forgot to translate each message... add your Chinese translation for each message in the file.

**Comment by morisenmen** [comment]
There is no need to translate anything.It's just need this file,here.

2015-05-26 18:01 GMT+08:00 Kartik Visweswaran <notifications@github.com>:

**Comment by kartik-v** [comment]
Check the other language files like [russian](https://github.com/kartik-v/yii2-widget-datetimepicker/blob/master/messages/ru/kvdatetime.php) or [german](https://github.com/kartik-v/yii2-widget-datetimepicker/blob/master/messages/de/kvdatetime.php).

Do not submit a blank message file... if you do not need translations- just set the `language` property of the widget to `en` - it will work.

**Comment by kartik-v** [comment]
Check the other language files like [russian](https://github.com/kartik-v/yii2-widget-datetimepicker/blob/master/messages/ru/kvdatetime.php) or [german](https://github.com/kartik-v/yii2-widget-datetimepicker/blob/master/messages/de/kvdatetime.php).

Do not submit a blank message file... if you do not need translations- just set the `language` property of the widget to  `en` (english).

If you on the other hand need chinese translations, then edit the file to have Chinese messages and resubmit the PR.

**Comment by morisenmen** [comment]
ok,add translation infomations

**Pull request merged**
